# compared with nanodet-m_hand_old, I 
# 1. set keep_ratio = False (for tensorrt fix input size)
# 2. add new train samples
#Config File example
save_dir: workspace/nanodet_m_hand
model:
  arch:
    name: OneStageDetector
    backbone:
      name: ShuffleNetV2
      model_size: 1.0x
      out_stages: [2,3,4]
      activation: LeakyReLU
    fpn:
      name: PAN
      in_channels: [116, 232, 464]
      out_channels: 96
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 3
      input_channel: 96
      feat_channels: 96
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
data:
  train:
    name: CustomHandCocoDataset
    # img_path: coco/train2017
    # ann_path: coco/annotations/instances_train2017.json
    img_path: None  # saved in anno file
    ann_path: /home/zg/wdir/zg/moyu/GestureDet/Datasets/train_val_jsons/train_od.json
    input_size: [320,320] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.6, 1.4]
      saturation: [0.5, 1.2]
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
  val:
    name: CustomHandCocoDataset
    # img_path: coco/val2017
    # ann_path: coco/annotations/instances_val2017.json
    img_path: None
    ann_path: /home/zg/wdir/zg/moyu/GestureDet/Datasets/train_val_jsons/val_od.json
    input_size: [320,320] #[w,h]
    keep_ratio: False
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
device:
  gpu_ids: [0]
  workers_per_gpu: 8
  batchsize_per_gpu: 192
schedule:
  # resume:
  load_model: '/home/zg/wdir/zg/moyu/GestureDet/LightGestureDet/nanodet/workspace/pretrained/nanodet_m.ckpt'
  optimizer:
    name: SGD
    lr: 0.14
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 300
    ratio: 0.1
  total_epochs: 280
  lr_schedule:
    name: MultiStepLR
    milestones: [240,260,275]
    gamma: 0.1
  val_intervals: 1 #10
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 10

class_names: ['person', 'hand', 'others']

